# GitHub Actions Workflow cho User Pages Deployment
# File này sẽ thay thế .github/workflows/deploy.yml hiện tại

name: Deploy to GitHub Pages User Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cấp quyền cần thiết cho GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một deployment chạy cùng lúc
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci --force --legacy-peer-deps
    
    - name: Build production
      run: |
        npm run build
    
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
    
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# Hướng dẫn sử dụng:
# 1. Tạo repository mới tên 'quochuannn.github.io'
# 2. Copy file này vào .github/workflows/deploy.yml trong repository mới
# 3. Đảm bảo vite.config.ts có base: '/'
# 4. Push code lên main branch
# 5. Vào Settings > Pages > Source: GitHub Actions